on:
  push:
    branches: [main]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        env:
          TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Token value: $TOKEN"
